//! Device models. Milestone 1: COM1 data port + debug port 0x402.
//! Milestone 2 (serial): COM2 (`0x2F8`–`0x2FF`) mirrors COM1 16550 debug UART.
//! Milestone 2 (partial): 8259 PIC ICW+OCW/IRQ; 8254 PIT ch0+ch2/port 0x61 speaker;
//! CMOS/RTC IRQ8; 8042/PS2 on MachineBus 0x60/0x64 (IRQ1 + scancode inject + A20);
//! System Control Port A 0x92 (Fast Gate A20 + fast reset);
//! APM/SMI ports 0xB2/0xB3 (APM_CNT/APM_STS + SMM handshake stub);
//! 8237A DMA register/page stubs (no transfer engine);
//! VGA text frame buffer MMIO stub at 0xB8000 + CRTC 0x3D4/0x3D5 noop;
//! VGA plane decode (Map Mask/Chain-4/Odd-Even/Extended Memory) + Graphics Controller
//! host read/write data path over four maps and the GC Misc CPU window (no display fetch);
//! PCI configuration mechanism #1 stub (0xCF8/0xCFC) + PIIX ISA/IDE/USB/ACPI functions;
//! PIIX primary BMIDE PRD walker, read and write directions (no ATA DMA command engine);
//! Primary IDE IDENTIFY + READ/WRITE SECTORS PIO + IRQ14 + 0xA1 ABRT stub (1F0–1F7/3F6);
//! IDE Device 0 only selection rules + 48-bit READ/WRITE SECTOR(S) EXT PIO;
//! Secondary IDE thin remap (170–177/376) + IRQ15;
//! 82077AA FDC port stub (0x3F0–0x3F5/0x3F7; Specify/Recalibrate/Seek/Sense Int; IRQ6);
//! FDC READ ID track scan and Configure EIS implied seek (1.44MB media only);
//! QEMU fw_cfg I/O subset (0x510/0x511 traditional + 0x514 DMA read/skip/select).
//! Classic LPT1/LPT2 parallel-port register-file stub (0x378–0x37A / 0x278–0x27A).
//! Local APIC MMIO identity stub at 0xFEE00000 (ID/Version; no delivery).
//! HPET MMIO capability stub at 0xFED00000 (CAPS/ID; counter stuck at 0).
//! I/O APIC MMIO stub at 0xFEC00000 (IOREGSEL/IOWIN + 24-entry RTE stub).

#![forbid(unsafe_code)]

mod apm;
mod cmos;
mod dma;
mod fdc;
mod fw_cfg;
mod hpet;
mod i8042;
mod ide;
mod ioapic;
mod lapic;
mod lpt;
mod pci;
mod pic;
mod pit;
mod port92;
mod serial;
mod vga;

pub use apm::{ApmSmi, APM_CNT_PORT, APM_STS_PORT};

pub use cmos::{
    CmosRtc, CMOS_BASE_MEMORY_MAX_KB, CMOS_CHECKSUM_FIRST, CMOS_CHECKSUM_LAST, CMOS_DATA,
    CMOS_EXT_MEMORY_MAX_KB, CMOS_INDEX, CMOS_MEM_ABOVE_16M_BLOCK_BYTES,
    CMOS_MEM_ABOVE_16M_MAX_BLOCKS, CMOS_MEM_ABOVE_4G_BLOCK_BYTES, CMOS_MEM_ABOVE_4G_MAX_BLOCKS,
    DIAG_ADAPTERS_MISMATCH, DIAG_ADAPTER_ID_TIMEOUT, DIAG_BAD_CHECKSUM, DIAG_BAD_CONFIG,
    DIAG_CLOCK_LOST_POWER, DIAG_DISK_INIT_FAILED, DIAG_MEMORY_SIZE_ERROR, DIAG_TIME_INVALID,
    EQUIP_DISPLAY_CGA_40, EQUIP_DISPLAY_CGA_80, EQUIP_DISPLAY_EGA_VGA, EQUIP_DISPLAY_ENABLED,
    EQUIP_DISPLAY_MASK, EQUIP_DISPLAY_MDA, EQUIP_FLOPPY_COUNT_MASK, EQUIP_FLOPPY_COUNT_SHIFT,
    EQUIP_FLOPPY_INSTALLED, EQUIP_KEYBOARD_ENABLED, EQUIP_MATH_COPROCESSOR, HOUR_PM,
    REG_BASE_MEM_HIGH, REG_BASE_MEM_LOW, REG_BOOT_OPTIONS, REG_CHECKSUM_HIGH, REG_CHECKSUM_LOW,
    REG_DIAGNOSTIC, REG_EQUIPMENT, REG_EXT_MEM2_HIGH, REG_EXT_MEM2_LOW, REG_EXT_MEM_HIGH,
    REG_EXT_MEM_LOW, REG_FLOPPY_TYPE, REG_HARD_DISK0_EXT_TYPE, REG_HARD_DISK0_PARAMS,
    REG_HARD_DISK1_EXT_TYPE, REG_HARD_DISK1_PARAMS, REG_HARD_DISK_TYPE, REG_MEM_ABOVE_16M_HIGH,
    REG_MEM_ABOVE_16M_LOW, REG_MEM_ABOVE_4G_HIGH, REG_MEM_ABOVE_4G_LOW, REG_MEM_ABOVE_4G_MID,
    REG_SHUTDOWN, REG_STATUS_A, REG_STATUS_B, REG_STATUS_C, REG_STATUS_D, SHUTDOWN_BLOCK_MOVE,
    SHUTDOWN_INT19, SHUTDOWN_JMP, SHUTDOWN_JMP_WITH_EOI, SHUTDOWN_SOFT_OR_UNEXPECTED, STATUS_A_UIP,
    STB_24_12, STB_AIE, STB_DM, STB_PIE, STB_SET, STB_UIE, STC_AF, STC_IRQF, STC_PF, STC_UF,
    UIP_WINDOW_PERIODS,
};
pub use dma::{
    Dma8237, DmaChannel, DmaController, DmaTransferError, DMA_MASTER_BASE, DMA_PAGE_CH0,
    DMA_PAGE_CH1, DMA_PAGE_CH2, DMA_PAGE_CH3, DMA_PAGE_CH4, DMA_PAGE_CH5, DMA_PAGE_CH6,
    DMA_PAGE_CH7, DMA_SLAVE_BASE,
};
pub use fdc::{
    Fdc82077, FDC_1440_CYLINDERS, FDC_1440_HEADS, FDC_1440_IMAGE_SIZE, FDC_1440_SECTORS_PER_TRACK,
    FDC_CMD_CONFIGURE, FDC_CMD_DUMPREG, FDC_CMD_FORMAT_TRACK, FDC_CMD_FORMAT_TRACK_MFM,
    FDC_CMD_MFM, FDC_CMD_PERPENDICULAR, FDC_CMD_READ_DATA, FDC_CMD_READ_ID, FDC_CMD_READ_ID_MFM,
    FDC_CMD_READ_TRACK, FDC_CMD_READ_TRACK_MFM, FDC_CMD_RECALIBRATE, FDC_CMD_RELATIVE_SEEK,
    FDC_CMD_RELATIVE_SEEK_DIR, FDC_CMD_RELATIVE_SEEK_IN, FDC_CMD_SEEK, FDC_CMD_SENSE_DRIVE_STATUS,
    FDC_CMD_SENSE_INT, FDC_CMD_SPECIFY, FDC_CMD_VERIFY, FDC_CMD_VERSION, FDC_CMD_WRITE_DATA,
    FDC_DIR_CCR, FDC_DIR_DSKCHG, FDC_DOR, FDC_DOR_DMA_IRQ, FDC_DOR_RESET_N, FDC_DSR_SOFTWARE_RESET,
    FDC_DUMPREG_RESULT_LEN, FDC_FIFO, FDC_MSR, FDC_MSR_DIO, FDC_MSR_RQM, FDC_READ_ID_RESULT_LEN,
    FDC_SECTOR_N, FDC_SECTOR_SIZE, FDC_SRA, FDC_SRB, FDC_ST0_HEAD, FDC_ST0_IC_ABNORMAL,
    FDC_ST0_IC_NORMAL, FDC_ST0_IC_READY_CHANGE, FDC_ST0_SEEK_END, FDC_ST1_EN, FDC_ST1_MA,
    FDC_ST1_ND, FDC_ST1_NW, FDC_ST3_HEAD, FDC_ST3_RESERVED_BIT3, FDC_ST3_RESERVED_BIT5,
    FDC_ST3_TRACK0, FDC_ST3_UNIT_MASK, FDC_ST3_WRITE_PROTECT, FDC_TDR, FDC_VERSION_82077AA,
};
pub use fw_cfg::{
    cfg_id_value, E820Entry, FwCfg, FwCfgDmaError, FwCfgDmaOutcome, FwCfgItem, E820_TYPE_ACPI,
    E820_TYPE_MEMORY, E820_TYPE_NVS, E820_TYPE_RESERVED, E820_TYPE_UNUSABLE, FW_CFG_DATA,
    FW_CFG_DEFAULT_CPU_COUNT, FW_CFG_DMA_ACCESS_SIZE, FW_CFG_DMA_ADDR_HIGH, FW_CFG_DMA_ADDR_LOW,
    FW_CFG_DMA_ADDR_SIZE, FW_CFG_DMA_CTL_ERROR, FW_CFG_DMA_CTL_READ, FW_CFG_DMA_CTL_SELECT,
    FW_CFG_DMA_CTL_SKIP, FW_CFG_DMA_CTL_WRITE, FW_CFG_DMA_SIGNATURE, FW_CFG_E820_ENTRY_SIZE,
    FW_CFG_FILE_BOOTORDER, FW_CFG_FILE_DIR, FW_CFG_FILE_E820, FW_CFG_FILE_FIRST,
    FW_CFG_FILE_MAX_CPUS, FW_CFG_FILE_NAME_MAX, FW_CFG_FILE_SYSTEM_STATES, FW_CFG_ID,
    FW_CFG_MAX_CPUS, FW_CFG_NB_CPUS, FW_CFG_NOGRAPHIC, FW_CFG_RAM_SIZE, FW_CFG_SELECTOR,
    FW_CFG_SEL_WRITE, FW_CFG_SIGNATURE, FW_CFG_SIGNATURE_BYTES, FW_CFG_SYSTEM_STATES_SIZE,
    FW_CFG_SYSTEM_STATE_ENABLED, FW_CFG_TEST_FILE_BYTES, FW_CFG_TEST_FILE_NAME, FW_CFG_UUID,
    FW_CFG_UUID_SIZE, FW_CFG_VERSION, FW_CFG_VERSION_DMA,
};
pub use hpet::{
    HpetMmio, HPET_CAPS_ID_VALUE, HPET_CFG_ENABLE, HPET_COUNTER_CLK_PERIOD_FS, HPET_DEFAULT_BASE,
    HPET_NUM_TIM_CAP, HPET_REG_CAPS_ID, HPET_REG_CONFIG, HPET_REG_MAIN_COUNTER, HPET_REV_ID,
    HPET_VENDOR_ID, HPET_WINDOW_SIZE,
};
pub use i8042::{
    CFG_AUX_CLOCK_DISABLE, CFG_INT1, CFG_INT12, CFG_KBD_CLOCK_DISABLE, CFG_TRANSLATE,
    CMD_DISABLE_AUX, CMD_DISABLE_KBD, CMD_ENABLE_AUX, CMD_ENABLE_KBD, CMD_PULSE_RESET,
    CMD_READ_CONFIG, CMD_READ_OUTPUT_PORT, CMD_SELF_TEST, CMD_TEST_AUX, CMD_TEST_KBD,
    CMD_WRITE_AUX, CMD_WRITE_CONFIG, CMD_WRITE_OUTPUT_PORT, I8042, I8042_DATA, I8042_STATUS_CMD,
    OUTPUT_PORT_A20, SELF_TEST_OK, STATUS_AUX_OBF, STATUS_CMD, STATUS_IBF, STATUS_OBF, STATUS_SYS,
    TEST_AUX_OK, TEST_KBD_OK,
};
pub use ide::{
    IdePrimary, IdeSecondary, ATAPI_ASC_INVALID_COMMAND_OPERATION_CODE,
    ATAPI_ASC_INVALID_FIELD_IN_CDB, ATAPI_ASC_LBA_OUT_OF_RANGE, ATAPI_ASC_MEDIUM_NOT_PRESENT,
    ATAPI_CDROM_BLOCK_BYTES, ATAPI_CMD_INQUIRY, ATAPI_CMD_READ_10, ATAPI_CMD_READ_CAPACITY,
    ATAPI_CMD_REQUEST_SENSE, ATAPI_CMD_TEST_UNIT_READY, ATAPI_FEATURE_DMA, ATAPI_FEATURE_OVL,
    ATAPI_INQUIRY_DATA_BYTES, ATAPI_INQUIRY_EVPD, ATAPI_INQUIRY_RESPONSE_DATA_FORMAT,
    ATAPI_INQUIRY_RMB, ATAPI_IR_CD, ATAPI_IR_IO, ATAPI_IR_REL, ATAPI_PACKET_BYTES,
    ATAPI_PERIPHERAL_DEVICE_TYPE_CDROM, ATAPI_PERIPHERAL_DEVICE_TYPE_UNKNOWN,
    ATAPI_READ_CAPACITY_DATA_BYTES, ATAPI_SENSE_DATA_BYTES, ATAPI_SENSE_ILLEGAL_REQUEST,
    ATAPI_SENSE_NOT_READY, ATAPI_SENSE_NO_SENSE, ATAPI_SENSE_RESPONSE_CODE_CURRENT,
    ATAPI_SIGNATURE_LBA_HIGH, ATAPI_SIGNATURE_LBA_LOW, ATAPI_SIGNATURE_LBA_MID,
    ATAPI_SIGNATURE_SECTOR_COUNT, ATA_CMD_DEVICE_RESET, ATA_CMD_DIAGNOSTIC, ATA_CMD_IDENTIFY,
    ATA_CMD_IDENTIFY_PACKET, ATA_CMD_PACKET, ATA_CMD_READ_SECTORS, ATA_CMD_READ_SECTORS_EXT,
    ATA_CMD_READ_VERIFY_SECTORS, ATA_CMD_SMART, ATA_CMD_WRITE_SECTORS, ATA_CMD_WRITE_SECTORS_EXT,
    ATA_CMD_WRITE_VERIFY_SECTORS, ATA_DC_HOB, ATA_DC_NIEN, ATA_DC_SRST, ATA_DIAG_PASSED,
    ATA_DRIVE_LBA, ATA_DRIVE_SLAVE, ATA_ER_ABRT, ATA_ER_IDNF, ATA_LBA28_MAX_SECTORS,
    ATA_LBA48_MAX_SECTORS, ATA_SIGNATURE_LBA_HIGH, ATA_SIGNATURE_LBA_LOW, ATA_SIGNATURE_LBA_MID,
    ATA_SIGNATURE_SECTOR_COUNT, ATA_SR_BSY, ATA_SR_DRDY, ATA_SR_DRQ, ATA_SR_DSC, ATA_SR_ERR,
    IDE_PRIMARY_CTRL, IDE_PRIMARY_DATA, IDE_PRIMARY_DRIVE, IDE_PRIMARY_ERROR, IDE_PRIMARY_LBA_HI,
    IDE_PRIMARY_LBA_LO, IDE_PRIMARY_LBA_MID, IDE_PRIMARY_SECCOUNT, IDE_PRIMARY_STATUS,
    IDE_SECONDARY_CTRL, IDE_SECONDARY_DATA, IDE_SECONDARY_DRIVE, IDE_SECONDARY_ERROR,
    IDE_SECONDARY_LBA_HI, IDE_SECONDARY_LBA_LO, IDE_SECONDARY_LBA_MID, IDE_SECONDARY_SECCOUNT,
    IDE_SECONDARY_STATUS,
};
pub use ioapic::{
    IoApicMmio, IOAPIC_DEFAULT_BASE, IOAPIC_IND_ARB, IOAPIC_IND_ID, IOAPIC_IND_REDTBL0,
    IOAPIC_IND_VER, IOAPIC_IOREGSEL, IOAPIC_IOWIN, IOAPIC_MAX_REDIRECTION_ENTRY,
    IOAPIC_REDIRECTION_COUNT, IOAPIC_VERSION_ID, IOAPIC_VER_VALUE, IOAPIC_WINDOW_SIZE,
};
pub use lapic::{
    LocalApicMmio, LAPIC_DEFAULT_BASE, LAPIC_MAX_LVT_ENTRY, LAPIC_REG_ID, LAPIC_REG_VERSION,
    LAPIC_VERSION_ID, LAPIC_VERSION_VALUE, LAPIC_WINDOW_SIZE,
};
pub use lpt::{
    ParallelPort, LPT1_BASE, LPT2_BASE, LPT_CONTROL, LPT_DATA, LPT_LAST_OFFSET, LPT_STATUS,
    LPT_STATUS_BUSY_N, LPT_STATUS_NO_PRINTER,
};
pub use pci::{
    decode_bmide_prd, pirqrc_routed_irq, sanitize_piix_elcr, BmidePrdEntry, BmidePrdError,
    BmidePrdTransfer, FdhcHole, PamRegion, PciBarSpec, PciConfig, SmramRegion,
    ACPI_PM1_CNT_GBL_RLS, ACPI_PM1_CNT_SCI_EN, ACPI_PM1_CNT_SLP_EN, ACPI_PM1_CNT_SLP_TYP_MASK,
    ACPI_PM1_CNT_STICKY_MASK, ACPI_PM1_EN_GBL, ACPI_PM1_EN_PWRBTN, ACPI_PM1_EN_TMR,
    ACPI_PM1_EN_WRITABLE_MASK, ACPI_PM1_STS_GBL, ACPI_PM1_STS_PWRBTN, ACPI_PM1_STS_SCI_MASK,
    ACPI_PM1_STS_TMR, ACPI_PM1_STS_WRITE_CLEAR_MASK, ACPI_PM_TIMER_BITS, ACPI_PM_TIMER_HZ,
    ACPI_PM_TIMER_MASK, PCI_BAR0_OFFSET, PCI_BAR_COUNT, PCI_BAR_IO_RESERVED, PCI_BAR_IO_SPACE,
    PCI_BAR_MEM_PREFETCHABLE, PCI_BAR_MEM_TYPE_32BIT, PCI_BAR_MEM_TYPE_64BIT,
    PCI_BAR_MEM_TYPE_MASK, PCI_BAR_REGION_END, PCI_BIST_OFFSET, PCI_CACHE_LINE_SIZE_OFFSET,
    PCI_CAP_POINTER_OFFSET, PCI_CARDBUS_CIS_OFFSET, PCI_CLASS_BRIDGE, PCI_CLASS_SERIAL_BUS,
    PCI_CLASS_STORAGE, PCI_COMMAND_BUS_MASTER, PCI_COMMAND_IO, PCI_COMMAND_MEM, PCI_COMMAND_OFFSET,
    PCI_CONFIG_ADDRESS, PCI_CONFIG_DATA, PCI_DEVICE_I440FX, PCI_DEVICE_PIIX3_IDE,
    PCI_DEVICE_PIIX3_ISA, PCI_DEVICE_PIIX3_USB, PCI_DEVICE_PIIX_ACPI, PCI_HEADER_MULTIFUNCTION,
    PCI_HEADER_TYPE_OFFSET, PCI_HOST_BRIDGE_CACHE_LINE_SIZE_DEFAULT, PCI_HOST_BRIDGE_COMMAND_MASK,
    PCI_HOST_BRIDGE_LATENCY_TIMER_DEFAULT, PCI_HOST_BRIDGE_STATUS_STUB, PCI_INTERRUPT_LINE_OFFSET,
    PCI_INTERRUPT_PIN_OFFSET, PCI_LATENCY_TIMER_OFFSET, PCI_MAX_LAT_OFFSET, PCI_MIN_GNT_OFFSET,
    PCI_PIIX_ACPI_COMMAND_MASK, PCI_PIIX_ACPI_PM1A_CNT, PCI_PIIX_ACPI_PM1A_EVT,
    PCI_PIIX_ACPI_PMBASE_MASK, PCI_PIIX_ACPI_PMBASE_OFFSET, PCI_PIIX_ACPI_PM_IO_SIZE,
    PCI_PIIX_ACPI_PM_TMR, PCI_PIIX_ACPI_STATUS_STUB, PCI_PIIX_IDE_BMIBA_MASK,
    PCI_PIIX_IDE_BMIBA_OFFSET, PCI_PIIX_IDE_BMICOM_PRIMARY, PCI_PIIX_IDE_BMICOM_RWCON,
    PCI_PIIX_IDE_BMICOM_SECONDARY, PCI_PIIX_IDE_BMICOM_SSBM, PCI_PIIX_IDE_BMIDE_IO_SIZE,
    PCI_PIIX_IDE_BMIDTP_PRIMARY, PCI_PIIX_IDE_BMIDTP_SECONDARY, PCI_PIIX_IDE_BMISTA_ACTIVE,
    PCI_PIIX_IDE_BMISTA_ERROR, PCI_PIIX_IDE_BMISTA_PRIMARY, PCI_PIIX_IDE_BMISTA_SECONDARY,
    PCI_PIIX_IDE_COMMAND_MASK, PCI_PIIX_IDE_IDETIM_OFFSET, PCI_PIIX_IDE_PRD_BYTE_COUNT_64K,
    PCI_PIIX_IDE_PRD_ENTRY_SIZE, PCI_PIIX_IDE_PRD_EOT, PCI_PIIX_IDE_STATUS_STUB,
    PCI_PIIX_ISA_COMMAND_MASK, PCI_PIIX_ISA_PIRQRC_DEFAULT, PCI_PIIX_ISA_PIRQRC_DISABLE,
    PCI_PIIX_ISA_PIRQRC_IRQ_MASK, PCI_PIIX_ISA_PIRQRC_OFFSET, PCI_PIIX_ISA_STATUS_STUB,
    PCI_PIIX_USB_BAR0_MASK, PCI_PIIX_USB_BAR0_OFFSET, PCI_PIIX_USB_COMMAND_MASK,
    PCI_PIIX_USB_LEGSUP_OFFSET, PCI_PIIX_USB_STATUS_STUB, PCI_PIIX_USB_UHCI_FLBASEADD,
    PCI_PIIX_USB_UHCI_FRNUM, PCI_PIIX_USB_UHCI_IO_SIZE, PCI_PIIX_USB_UHCI_PORTSC1,
    PCI_PIIX_USB_UHCI_PORTSC2, PCI_PIIX_USB_UHCI_SOFMOD, PCI_PIIX_USB_UHCI_USBCMD,
    PCI_PIIX_USB_UHCI_USBINTR, PCI_PIIX_USB_UHCI_USBSTS, PCI_PMC_FDHC_15M_END,
    PCI_PMC_FDHC_15M_START, PCI_PMC_FDHC_512K_END, PCI_PMC_FDHC_512K_START, PCI_PMC_FDHC_DEFAULT,
    PCI_PMC_FDHC_HEN_15M_16M, PCI_PMC_FDHC_HEN_512K_640K, PCI_PMC_FDHC_HEN_NONE,
    PCI_PMC_FDHC_HEN_RESERVED, PCI_PMC_FDHC_HEN_SHIFT, PCI_PMC_FDHC_OFFSET,
    PCI_PMC_FDHC_WRITABLE_MASK, PCI_PMC_PAM0_OFFSET, PCI_PMC_PAM0_WRITABLE_MASK, PCI_PMC_PAM_COUNT,
    PCI_PMC_PAM_DEFAULT, PCI_PMC_PAM_FIELD_MASK, PCI_PMC_PAM_RE, PCI_PMC_PAM_REGION_COUNT,
    PCI_PMC_PAM_WE, PCI_PMC_PAM_WRITABLE_MASK, PCI_PMC_SMRAM_COMPAT_END,
    PCI_PMC_SMRAM_COMPAT_START, PCI_PMC_SMRAM_C_BASE_SEG_A0000, PCI_PMC_SMRAM_C_BASE_SEG_MASK,
    PCI_PMC_SMRAM_DEFAULT, PCI_PMC_SMRAM_D_CLS, PCI_PMC_SMRAM_D_LCK, PCI_PMC_SMRAM_D_OPEN,
    PCI_PMC_SMRAM_G_SMRAME, PCI_PMC_SMRAM_OFFSET, PCI_PMC_SMRAM_WRITABLE_MASK, PCI_PROG_IF_UHCI,
    PCI_ROM_BAR_OFFSET, PCI_STATUS_CAP_LIST, PCI_STATUS_DETECTED_PARITY, PCI_STATUS_DEVSEL_MASK,
    PCI_STATUS_DEVSEL_MEDIUM, PCI_STATUS_FAST_BACK, PCI_STATUS_OFFSET, PCI_STATUS_PARITY,
    PCI_STATUS_REC_MASTER_ABORT, PCI_STATUS_REC_TARGET_ABORT, PCI_STATUS_RW1C_MASK,
    PCI_STATUS_SIG_SYSTEM_ERROR, PCI_STATUS_SIG_TARGET_ABORT, PCI_SUBCLASS_HOST_BRIDGE,
    PCI_SUBCLASS_IDE, PCI_SUBCLASS_ISA_BRIDGE, PCI_SUBCLASS_OTHER_BRIDGE, PCI_SUBCLASS_USB,
    PCI_SUBSYSTEM_ID_OFFSET, PCI_SUBSYSTEM_VENDOR_ID_OFFSET, PCI_VENDOR_INTEL, PIIX_ELCR_MASTER,
    PIIX_ELCR_MASTER_WRITABLE, PIIX_ELCR_SLAVE, PIIX_ELCR_SLAVE_WRITABLE,
};
pub use pic::{DualPic, Pic8259, PIC_MASTER_CMD, PIC_MASTER_DATA, PIC_SLAVE_CMD, PIC_SLAVE_DATA};
pub use pit::{
    Pit8254, PitChannel, PIT_CH0_DATA, PIT_CH1_DATA, PIT_CH2_DATA, PIT_CONTROL, PORT61_GATE2,
    PORT61_OUT2, PORT61_SPKR_DATA, PORT_SYSTEM_CONTROL,
};
pub use port92::{Port92, PORT92_A20, PORT92_RESET, PORT_SYSTEM_CONTROL_A};
pub use serial::{DebugConsole, Serial16550, SerialOutput};
pub use vga::{
    vga_dac_default_ram, VgaFrame, VgaPlaneAccess, VgaPlaneAddressing, VgaRenderMode, VgaText,
    VBE_INFO_BLOCK_BYTES, VBE_MODE_03H_TEXT, VBE_MODE_0DH_PLANAR, VBE_MODE_0EH_PLANAR,
    VBE_MODE_10H_PLANAR, VBE_MODE_12H_PLANAR, VBE_MODE_13H_CHAIN4, VBE_MODE_INFO_BLOCK_BYTES,
    VBE_SUPPORTED_MODES, VGA_APERTURE_BASE, VGA_APERTURE_END, VGA_APERTURE_SIZE,
    VGA_ATC_ADDRESS_DATA, VGA_ATC_COLOR_PLANE_ENABLE, VGA_ATC_COLOR_PLANE_ENABLE_DEFAULT,
    VGA_ATC_COLOR_SELECT, VGA_ATC_COLOR_SELECT_DEFAULT, VGA_ATC_DATA_READ, VGA_ATC_DEFAULTS,
    VGA_ATC_HORIZONTAL_PEL_PANNING, VGA_ATC_HORIZONTAL_PEL_PANNING_DEFAULT, VGA_ATC_INDEX_DEFAULT,
    VGA_ATC_MODE_8BIT, VGA_ATC_MODE_ATGE, VGA_ATC_MODE_BLINK, VGA_ATC_MODE_CONTROL,
    VGA_ATC_MODE_CONTROL_DEFAULT, VGA_ATC_MODE_LINE_GRAPHICS, VGA_ATC_MODE_P54S,
    VGA_ATC_OVERSCAN_COLOR, VGA_ATC_OVERSCAN_COLOR_DEFAULT, VGA_ATC_PAS, VGA_ATC_REG_COUNT,
    VGA_CELL_BYTES, VGA_CRTC_CURSOR_DISABLE, VGA_CRTC_CURSOR_END, VGA_CRTC_CURSOR_LOC_HIGH,
    VGA_CRTC_CURSOR_LOC_LOW, VGA_CRTC_CURSOR_SCANLINE_MASK, VGA_CRTC_CURSOR_START, VGA_CRTC_DATA,
    VGA_CRTC_DATA_MONO, VGA_CRTC_HORIZONTAL_DISPLAY_END, VGA_CRTC_INDEX, VGA_CRTC_INDEX_MONO,
    VGA_CRTC_MAX_SCAN_DOUBLING, VGA_CRTC_MAX_SCAN_LINE, VGA_CRTC_MAX_SCAN_LINE_COMPARE_BIT9,
    VGA_CRTC_MAX_SCAN_LINE_DEFAULT, VGA_CRTC_MAX_SCAN_MASK, VGA_CRTC_MAX_SCAN_START_VBLANK_BIT9,
    VGA_CRTC_MODE_BYTE_ADDRESSING, VGA_CRTC_MODE_CONTROL, VGA_CRTC_OFFSET, VGA_CRTC_OFFSET_DEFAULT,
    VGA_CRTC_OVERFLOW, VGA_CRTC_OVERFLOW_LINE_COMPARE_BIT8, VGA_CRTC_OVERFLOW_START_VBLANK_BIT8,
    VGA_CRTC_OVERFLOW_VDE_BIT8, VGA_CRTC_OVERFLOW_VDE_BIT9, VGA_CRTC_OVERFLOW_VRS_BIT8,
    VGA_CRTC_OVERFLOW_VRS_BIT9, VGA_CRTC_OVERFLOW_VT_BIT8, VGA_CRTC_OVERFLOW_VT_BIT9,
    VGA_CRTC_PROTECT, VGA_CRTC_REG_COUNT, VGA_CRTC_START_ADDR_HIGH,
    VGA_CRTC_START_ADDR_HIGH_DEFAULT, VGA_CRTC_START_ADDR_LOW, VGA_CRTC_START_ADDR_LOW_DEFAULT,
    VGA_CRTC_UNDERLINE_DIV4, VGA_CRTC_UNDERLINE_DW, VGA_CRTC_UNDERLINE_LOCATION,
    VGA_CRTC_UNDERLINE_LOCATION_DEFAULT, VGA_CRTC_UNDERLINE_MASK, VGA_CRTC_VERTICAL_DISPLAY_END,
    VGA_CRTC_VERTICAL_RETRACE_END, VGA_DAC_CGA16_DEFAULTS, VGA_DAC_COLOR_MASK, VGA_DAC_DATA,
    VGA_DAC_ENTRY_COUNT, VGA_DAC_PEL_MASK, VGA_DAC_PEL_MASK_DEFAULT, VGA_DAC_READ_INDEX,
    VGA_DAC_STATE_READ, VGA_DAC_STATE_WRITE, VGA_DAC_WRITE_INDEX, VGA_DEFAULT_ATTR,
    VGA_DEFAULT_CHAR, VGA_FONT_BANK_BYTES, VGA_FONT_GLYPH_BYTES, VGA_FONT_MAX_SCAN_LINES,
    VGA_FONT_PLANE, VGA_GC_BIT_MASK, VGA_GC_BIT_MASK_DEFAULT, VGA_GC_COLOR_COMPARE,
    VGA_GC_COLOR_DONT_CARE, VGA_GC_DATA, VGA_GC_DATA_ROTATE, VGA_GC_DATA_ROTATE_DEFAULT,
    VGA_GC_DEFAULTS, VGA_GC_ENABLE_SET_RESET, VGA_GC_ENABLE_SET_RESET_DEFAULT, VGA_GC_FUNCTION_AND,
    VGA_GC_FUNCTION_OR, VGA_GC_FUNCTION_REPLACE, VGA_GC_FUNCTION_SELECT_MASK, VGA_GC_FUNCTION_XOR,
    VGA_GC_INDEX, VGA_GC_MEMORY_MAP_A0000_128K, VGA_GC_MEMORY_MAP_A0000_64K,
    VGA_GC_MEMORY_MAP_B0000_32K, VGA_GC_MEMORY_MAP_B8000_32K, VGA_GC_MISC,
    VGA_GC_MISC_CHAIN_ODD_EVEN, VGA_GC_MISC_DEFAULT, VGA_GC_MISC_GRAPHICS_MODE,
    VGA_GC_MISC_MEMORY_MAP_MASK, VGA_GC_MISC_MEMORY_MAP_SHIFT, VGA_GC_MODE, VGA_GC_MODE_DEFAULT,
    VGA_GC_MODE_HOST_ODD_EVEN_READ, VGA_GC_MODE_READ, VGA_GC_MODE_SHIFT256,
    VGA_GC_MODE_SHIFT_INTERLEAVE, VGA_GC_MODE_WRITE_MASK, VGA_GC_READ_MAP_SELECT,
    VGA_GC_READ_MAP_SELECT_MASK, VGA_GC_REG_COUNT, VGA_GC_ROTATE_COUNT_MASK, VGA_GC_SET_RESET,
    VGA_GC_SET_RESET_DEFAULT, VGA_INPUT_STATUS_1, VGA_INPUT_STATUS_1_MONO,
    VGA_LINE_GRAPHICS_FIRST_CODE, VGA_LINE_GRAPHICS_LAST_CODE, VGA_MISC_CLOCK_25MHZ,
    VGA_MISC_CLOCK_28MHZ, VGA_MISC_CLOCK_SELECT, VGA_MISC_HSYNC_POLARITY, VGA_MISC_IOAS,
    VGA_MISC_OUTPUT_DEFAULT, VGA_MISC_OUTPUT_READ, VGA_MISC_OUTPUT_WRITE, VGA_MISC_RAM_ENABLE,
    VGA_MISC_VSYNC_POLARITY, VGA_MODE13_HEIGHT, VGA_MODE13_WIDTH, VGA_PLANAR16_DOTS_PER_BYTE,
    VGA_PLANE_COUNT, VGA_PLANE_SIZE, VGA_PLANE_SIZE_NO_EXTENDED, VGA_SEQ_CHAR_MAP_A_MASK,
    VGA_SEQ_CHAR_MAP_B_MASK, VGA_SEQ_CHAR_MAP_SELECT, VGA_SEQ_CHAR_MAP_SELECT_DEFAULT,
    VGA_SEQ_CLOCKING_8DOT, VGA_SEQ_CLOCKING_MODE, VGA_SEQ_DATA, VGA_SEQ_DEFAULTS, VGA_SEQ_INDEX,
    VGA_SEQ_MAP_MASK, VGA_SEQ_MAP_MASK_DEFAULT, VGA_SEQ_MAP_MASK_PLANES, VGA_SEQ_MEMORY_MODE,
    VGA_SEQ_MEMORY_MODE_CHAIN4, VGA_SEQ_MEMORY_MODE_DEFAULT, VGA_SEQ_MEMORY_MODE_EXTENDED,
    VGA_SEQ_MEMORY_MODE_ODD_EVEN_DISABLE, VGA_SEQ_REG_COUNT, VGA_STATUS1_DD,
    VGA_STATUS1_PHASE_PERIOD, VGA_STATUS1_VR, VGA_TEXT_ATTR_FONT_SELECT, VGA_TEXT_ATTR_PLANE,
    VGA_TEXT_BASE, VGA_TEXT_CELL_WIDTH_8DOT, VGA_TEXT_CELL_WIDTH_9DOT, VGA_TEXT_CHAR_PLANE,
    VGA_TEXT_COLS, VGA_TEXT_END, VGA_TEXT_ROWS, VGA_TEXT_SIZE, VGA_TEXT_UNDERLINE_BG_BITS,
    VGA_TEXT_UNDERLINE_FG_BITS, VGA_TEXT_UNDERLINE_FG_VALUE, VGA_WINDOW_A0000_BASE,
    VGA_WINDOW_B0000_BASE,
};

/// Port I/O sink shared by CLI and browser.
pub trait PortDevice {
    fn port_read(&mut self, port: u16, size: u8) -> u32;
    fn port_write(&mut self, port: u16, size: u8, value: u32);
}
