//! Device models. Milestone 1: COM1 data port + debug port 0x402.
//! Milestone 2 (partial): 8259 PIC ICW+OCW/IRQ; 8254 PIT ch0+ch2/port 0x61 speaker;
//! CMOS/RTC IRQ8; 8042/PS2 on MachineBus 0x60/0x64 (IRQ1 + scancode inject + A20);
//! 8237A DMA register/page stubs (no transfer engine);
//! VGA text frame buffer MMIO stub at 0xB8000 + CRTC 0x3D4/0x3D5 noop;
//! PCI configuration mechanism #1 stub (0xCF8/0xCFC) + PIIX ISA/IDE/USB/ACPI functions;
//! Primary IDE IDENTIFY + READ/WRITE SECTORS PIO + IRQ14 + 0xA1 ABRT stub (1F0–1F7/3F6);
//! Secondary IDE thin remap (170–177/376) + IRQ15;
//! 82077AA FDC port stub (0x3F0–0x3F5/0x3F7; Specify/Recalibrate/Seek/Sense Int; IRQ6; no media).

#![forbid(unsafe_code)]

mod cmos;
mod dma;
mod fdc;
mod i8042;
mod ide;
mod pci;
mod pic;
mod pit;
mod serial;
mod vga;

pub use cmos::{
    CmosRtc, CMOS_DATA, CMOS_INDEX, REG_SHUTDOWN, REG_STATUS_A, REG_STATUS_B, REG_STATUS_C,
    REG_STATUS_D, SHUTDOWN_BLOCK_MOVE, SHUTDOWN_INT19, SHUTDOWN_JMP, SHUTDOWN_JMP_WITH_EOI,
    SHUTDOWN_SOFT_OR_UNEXPECTED, STATUS_A_UIP, STB_AIE, STB_PIE, STB_SET, STB_UIE, STC_AF,
    STC_IRQF, STC_PF, STC_UF, UIP_WINDOW_PERIODS,
};
pub use dma::{
    Dma8237, DmaChannel, DmaController, DmaTransferError, DMA_MASTER_BASE, DMA_PAGE_CH0,
    DMA_PAGE_CH1, DMA_PAGE_CH2, DMA_PAGE_CH3, DMA_PAGE_CH4, DMA_PAGE_CH5, DMA_PAGE_CH6,
    DMA_PAGE_CH7, DMA_SLAVE_BASE,
};
pub use fdc::{
    Fdc82077, FDC_1440_CYLINDERS, FDC_1440_HEADS, FDC_1440_IMAGE_SIZE, FDC_1440_SECTORS_PER_TRACK,
    FDC_CMD_CONFIGURE, FDC_CMD_MFM, FDC_CMD_PERPENDICULAR, FDC_CMD_READ_DATA, FDC_CMD_RECALIBRATE,
    FDC_CMD_RELATIVE_SEEK, FDC_CMD_RELATIVE_SEEK_DIR, FDC_CMD_RELATIVE_SEEK_IN, FDC_CMD_SEEK,
    FDC_CMD_SENSE_DRIVE_STATUS, FDC_CMD_SENSE_INT, FDC_CMD_SPECIFY, FDC_CMD_VERSION,
    FDC_CMD_WRITE_DATA, FDC_DIR_CCR, FDC_DIR_DSKCHG, FDC_DOR, FDC_DOR_DMA_IRQ, FDC_DOR_RESET_N,
    FDC_FIFO, FDC_MSR, FDC_MSR_DIO, FDC_MSR_RQM, FDC_SECTOR_N, FDC_SECTOR_SIZE, FDC_SRA, FDC_SRB,
    FDC_ST0_HEAD, FDC_ST0_IC_ABNORMAL, FDC_ST0_IC_NORMAL, FDC_ST0_IC_READY_CHANGE,
    FDC_ST0_SEEK_END, FDC_ST1_EN, FDC_ST1_ND, FDC_ST1_NW, FDC_ST3_HEAD, FDC_ST3_RESERVED_BIT3,
    FDC_ST3_RESERVED_BIT5, FDC_ST3_TRACK0, FDC_ST3_UNIT_MASK, FDC_ST3_WRITE_PROTECT, FDC_TDR,
    FDC_VERSION_82077AA,
};
pub use i8042::{
    CFG_AUX_CLOCK_DISABLE, CFG_INT1, CFG_INT12, CFG_KBD_CLOCK_DISABLE, CFG_TRANSLATE,
    CMD_DISABLE_AUX, CMD_DISABLE_KBD, CMD_ENABLE_AUX, CMD_ENABLE_KBD, CMD_PULSE_RESET,
    CMD_READ_CONFIG, CMD_READ_OUTPUT_PORT, CMD_SELF_TEST, CMD_TEST_AUX, CMD_TEST_KBD,
    CMD_WRITE_AUX, CMD_WRITE_CONFIG, CMD_WRITE_OUTPUT_PORT, I8042, I8042_DATA, I8042_STATUS_CMD,
    OUTPUT_PORT_A20, SELF_TEST_OK, STATUS_AUX_OBF, STATUS_CMD, STATUS_IBF, STATUS_OBF, STATUS_SYS,
    TEST_AUX_OK, TEST_KBD_OK,
};
pub use ide::{
    IdePrimary, IdeSecondary, ATA_CMD_IDENTIFY, ATA_CMD_IDENTIFY_PACKET, ATA_CMD_PACKET,
    ATA_CMD_READ_SECTORS, ATA_CMD_READ_VERIFY_SECTORS, ATA_CMD_WRITE_SECTORS,
    ATA_CMD_WRITE_VERIFY_SECTORS, ATA_DC_NIEN, ATA_DC_SRST, ATA_DRIVE_LBA, ATA_DRIVE_SLAVE,
    ATA_ER_ABRT, ATA_SR_BSY, ATA_SR_DRDY, ATA_SR_DRQ, ATA_SR_DSC, ATA_SR_ERR, IDE_PRIMARY_CTRL,
    IDE_PRIMARY_DATA, IDE_PRIMARY_DRIVE, IDE_PRIMARY_ERROR, IDE_PRIMARY_LBA_HI, IDE_PRIMARY_LBA_LO,
    IDE_PRIMARY_LBA_MID, IDE_PRIMARY_SECCOUNT, IDE_PRIMARY_STATUS, IDE_SECONDARY_CTRL,
    IDE_SECONDARY_DATA, IDE_SECONDARY_DRIVE, IDE_SECONDARY_ERROR, IDE_SECONDARY_LBA_HI,
    IDE_SECONDARY_LBA_LO, IDE_SECONDARY_LBA_MID, IDE_SECONDARY_SECCOUNT, IDE_SECONDARY_STATUS,
};
pub use pci::{
    pirqrc_routed_irq, sanitize_piix_elcr, PciConfig, PCI_BAR_IO_SPACE, PCI_CACHE_LINE_SIZE_OFFSET,
    PCI_CLASS_BRIDGE, PCI_CLASS_SERIAL_BUS, PCI_CLASS_STORAGE, PCI_COMMAND_BUS_MASTER,
    PCI_COMMAND_IO, PCI_COMMAND_MEM, PCI_COMMAND_OFFSET, PCI_CONFIG_ADDRESS, PCI_CONFIG_DATA,
    PCI_DEVICE_I440FX, PCI_DEVICE_PIIX3_IDE, PCI_DEVICE_PIIX3_ISA, PCI_DEVICE_PIIX3_USB,
    PCI_DEVICE_PIIX_ACPI, PCI_HEADER_MULTIFUNCTION, PCI_HOST_BRIDGE_CACHE_LINE_SIZE_DEFAULT,
    PCI_HOST_BRIDGE_COMMAND_MASK, PCI_HOST_BRIDGE_LATENCY_TIMER_DEFAULT,
    PCI_HOST_BRIDGE_STATUS_STUB, PCI_LATENCY_TIMER_OFFSET, PCI_PIIX_ACPI_COMMAND_MASK,
    PCI_PIIX_ACPI_PM1A_CNT, PCI_PIIX_ACPI_PM1A_EVT, PCI_PIIX_ACPI_PMBASE_MASK,
    PCI_PIIX_ACPI_PMBASE_OFFSET, PCI_PIIX_ACPI_PM_IO_SIZE, PCI_PIIX_ACPI_PM_TMR,
    PCI_PIIX_ACPI_STATUS_STUB, PCI_PIIX_IDE_BMIBA_MASK, PCI_PIIX_IDE_BMIBA_OFFSET,
    PCI_PIIX_IDE_BMICOM_PRIMARY, PCI_PIIX_IDE_BMICOM_SECONDARY, PCI_PIIX_IDE_BMIDE_IO_SIZE,
    PCI_PIIX_IDE_BMIDTP_PRIMARY, PCI_PIIX_IDE_BMIDTP_SECONDARY, PCI_PIIX_IDE_BMISTA_PRIMARY,
    PCI_PIIX_IDE_BMISTA_SECONDARY, PCI_PIIX_IDE_COMMAND_MASK, PCI_PIIX_IDE_STATUS_STUB,
    PCI_PIIX_ISA_COMMAND_MASK, PCI_PIIX_ISA_PIRQRC_DEFAULT, PCI_PIIX_ISA_PIRQRC_DISABLE,
    PCI_PIIX_ISA_PIRQRC_IRQ_MASK, PCI_PIIX_ISA_PIRQRC_OFFSET, PCI_PIIX_ISA_STATUS_STUB,
    PCI_PIIX_USB_BAR0_MASK, PCI_PIIX_USB_BAR0_OFFSET, PCI_PIIX_USB_COMMAND_MASK,
    PCI_PIIX_USB_STATUS_STUB, PCI_PIIX_USB_UHCI_FLBASEADD, PCI_PIIX_USB_UHCI_FRNUM,
    PCI_PIIX_USB_UHCI_IO_SIZE, PCI_PIIX_USB_UHCI_PORTSC1, PCI_PIIX_USB_UHCI_PORTSC2,
    PCI_PIIX_USB_UHCI_SOFMOD, PCI_PIIX_USB_UHCI_USBCMD, PCI_PIIX_USB_UHCI_USBINTR,
    PCI_PIIX_USB_UHCI_USBSTS, PCI_PROG_IF_UHCI, PCI_STATUS_CAP_LIST, PCI_STATUS_DEVSEL_MASK,
    PCI_STATUS_DEVSEL_MEDIUM, PCI_STATUS_FAST_BACK, PCI_STATUS_OFFSET, PCI_STATUS_RW1C_MASK,
    PCI_SUBCLASS_HOST_BRIDGE, PCI_SUBCLASS_IDE, PCI_SUBCLASS_ISA_BRIDGE, PCI_SUBCLASS_OTHER_BRIDGE,
    PCI_SUBCLASS_USB, PCI_VENDOR_INTEL, PIIX_ELCR_MASTER, PIIX_ELCR_MASTER_WRITABLE,
    PIIX_ELCR_SLAVE, PIIX_ELCR_SLAVE_WRITABLE,
};
pub use pic::{DualPic, Pic8259, PIC_MASTER_CMD, PIC_MASTER_DATA, PIC_SLAVE_CMD, PIC_SLAVE_DATA};
pub use pit::{
    Pit8254, PitChannel, PIT_CH0_DATA, PIT_CH1_DATA, PIT_CH2_DATA, PIT_CONTROL, PORT61_GATE2,
    PORT61_OUT2, PORT61_SPKR_DATA, PORT_SYSTEM_CONTROL,
};
pub use serial::{DebugConsole, Serial16550, SerialOutput};
pub use vga::{
    vga_dac_default_ram, VgaText, VGA_CELL_BYTES, VGA_CRTC_CURSOR_DISABLE, VGA_CRTC_CURSOR_END,
    VGA_CRTC_CURSOR_LOC_HIGH, VGA_CRTC_CURSOR_LOC_LOW, VGA_CRTC_CURSOR_SCANLINE_MASK,
    VGA_CRTC_CURSOR_START, VGA_CRTC_DATA, VGA_CRTC_DATA_MONO, VGA_CRTC_INDEX, VGA_CRTC_INDEX_MONO,
    VGA_CRTC_MAX_SCAN_DOUBLING, VGA_CRTC_MAX_SCAN_LINE, VGA_CRTC_MAX_SCAN_LINE_COMPARE_BIT9,
    VGA_CRTC_MAX_SCAN_LINE_DEFAULT, VGA_CRTC_MAX_SCAN_MASK, VGA_CRTC_MAX_SCAN_START_VBLANK_BIT9,
    VGA_CRTC_OFFSET, VGA_CRTC_OFFSET_DEFAULT, VGA_CRTC_OVERFLOW,
    VGA_CRTC_OVERFLOW_LINE_COMPARE_BIT8, VGA_CRTC_OVERFLOW_START_VBLANK_BIT8,
    VGA_CRTC_OVERFLOW_VDE_BIT8, VGA_CRTC_OVERFLOW_VDE_BIT9, VGA_CRTC_OVERFLOW_VRS_BIT8,
    VGA_CRTC_OVERFLOW_VRS_BIT9, VGA_CRTC_OVERFLOW_VT_BIT8, VGA_CRTC_OVERFLOW_VT_BIT9,
    VGA_CRTC_PROTECT, VGA_CRTC_REG_COUNT, VGA_CRTC_START_ADDR_HIGH,
    VGA_CRTC_START_ADDR_HIGH_DEFAULT, VGA_CRTC_START_ADDR_LOW, VGA_CRTC_START_ADDR_LOW_DEFAULT,
    VGA_CRTC_UNDERLINE_DIV4, VGA_CRTC_UNDERLINE_DW, VGA_CRTC_UNDERLINE_LOCATION,
    VGA_CRTC_UNDERLINE_LOCATION_DEFAULT, VGA_CRTC_UNDERLINE_MASK, VGA_CRTC_VERTICAL_RETRACE_END,
    VGA_DAC_CGA16_DEFAULTS, VGA_DAC_COLOR_MASK, VGA_DAC_DATA, VGA_DAC_ENTRY_COUNT,
    VGA_DAC_PEL_MASK, VGA_DAC_PEL_MASK_DEFAULT, VGA_DAC_READ_INDEX, VGA_DAC_STATE_READ,
    VGA_DAC_STATE_WRITE, VGA_DAC_WRITE_INDEX, VGA_DEFAULT_ATTR, VGA_DEFAULT_CHAR, VGA_GC_BIT_MASK,
    VGA_GC_BIT_MASK_DEFAULT, VGA_GC_DATA, VGA_GC_DATA_ROTATE, VGA_GC_DATA_ROTATE_DEFAULT,
    VGA_GC_DEFAULTS, VGA_GC_ENABLE_SET_RESET, VGA_GC_ENABLE_SET_RESET_DEFAULT, VGA_GC_INDEX,
    VGA_GC_MODE, VGA_GC_MODE_DEFAULT, VGA_GC_REG_COUNT, VGA_GC_SET_RESET, VGA_GC_SET_RESET_DEFAULT,
    VGA_INPUT_STATUS_1, VGA_INPUT_STATUS_1_MONO, VGA_MISC_IOAS, VGA_MISC_OUTPUT_DEFAULT,
    VGA_MISC_OUTPUT_READ, VGA_MISC_OUTPUT_WRITE, VGA_SEQ_DATA, VGA_SEQ_DEFAULTS, VGA_SEQ_INDEX,
    VGA_SEQ_REG_COUNT, VGA_STATUS1_DD, VGA_STATUS1_PHASE_PERIOD, VGA_STATUS1_VR, VGA_TEXT_BASE,
    VGA_TEXT_COLS, VGA_TEXT_END, VGA_TEXT_ROWS, VGA_TEXT_SIZE,
};

/// Port I/O sink shared by CLI and browser.
pub trait PortDevice {
    fn port_read(&mut self, port: u16, size: u8) -> u32;
    fn port_write(&mut self, port: u16, size: u8, value: u32);
}
