#!/usr/bin/env bash
# Fetch and build SeaVGABIOS (the VGA BIOS option ROM shipped in the SeaBIOS
# tree) into firmware/seavgabios/.
#
# Intended hosts:
#   - Linux (native or CI) — preferred
#   - Windows WSL2; Git Bash only if a working i386-capable gcc is on PATH
#
# This script does NOT vendor SeaBIOS/SeaVGABIOS sources into Rust crates.
# Sources stay under firmware/seavgabios/.src/ (gitignored). Only the binary +
# manifest land in firmware/seavgabios/ for local use (*.bin gitignored until
# licensing review).
#
# Build configuration (verified against vgasrc/Kconfig at the pinned revision):
#   CONFIG_QEMU=y               "Build Target" choice; VGA_STANDARD_VGA needs it
#   CONFIG_VGA_STANDARD_VGA=y   "QEMU/Bochs Original IBM 256K VGA" — plain
#                               256 KB stdvga, no Cirrus/ATI/Bochs-DISPI SVGA
#   CONFIG_VGA_VBE=n            this emulator has no VBE; do not build a ROM
#                               that advertises one
#   CONFIG_VGA_PCI=n            this emulator's VGA is a legacy port-mapped
#                               device, not a PCI function, so no PCI ROM header
# CONFIG_BUILD_VGABIOS is not user-settable; it is `default !NO_VGABIOS`, so
# selecting a VGA hardware type turns it on. Output is $(OUT)vgabios.bin.
#
# Out of scope here: mapping the ROM at 0xC0000, an option-ROM scan in the
# emulator, SeaBIOS POST, OVMF.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OUT_DIR="${ROOT}/firmware/seavgabios"
SRC_DIR="${SEAVGABIOS_SRC_DIR:-${OUT_DIR}/.src}"
# Build tree and kconfig file are kept out of the source checkout's defaults so
# this build can share a checkout with build-seabios.sh without clobbering it.
BUILD_DIR="${SEAVGABIOS_BUILD_DIR:-${OUT_DIR}/.build}"
CONFIG_FILE="${SEAVGABIOS_CONFIG:-${OUT_DIR}/.config.seavgabios}"

# Pinned release — same SeaBIOS tree and revision as build-seabios.sh.
SEAVGABIOS_REPO="${SEAVGABIOS_REPO:-https://gitlab.com/qemu-project/seabios.git}"
SEAVGABIOS_REF="${SEAVGABIOS_REF:-rel-1.16.3}"
SEAVGABIOS_COMMIT="${SEAVGABIOS_COMMIT:-a6ed6b701f0a57db0569ab98b0661c12a6ec3ff8}"

JOBS="${JOBS:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 2)}"
PYTHON="${PYTHON:-python3}"

log() { printf '+ %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

check_host() {
  need_cmd git
  need_cmd make
  need_cmd "${PYTHON}"
  if ! command -v gcc >/dev/null 2>&1 && ! command -v clang >/dev/null 2>&1; then
    die "need gcc or clang (i386 / -m32 capable toolchain for SeaVGABIOS)"
  fi
  if command -v gcc >/dev/null 2>&1; then
    if ! echo 'int main(void){return 0;}' | gcc -m32 -x c - -o /dev/null 2>/dev/null; then
      printf 'warning: gcc -m32 probe failed; make may fail without gcc-multilib or a cross toolchain.\n' >&2
      printf '         Linux: sudo apt-get install build-essential gcc-multilib python3\n' >&2
      printf '         Windows: use WSL2/Ubuntu or Linux CI (see firmware/README.md).\n' >&2
    fi
  fi
}

fetch_sources() {
  mkdir -p "${OUT_DIR}"
  if [[ ! -d "${SRC_DIR}/.git" ]]; then
    log "clone ${SEAVGABIOS_REPO} -> ${SRC_DIR}"
    git clone --filter=blob:none "${SEAVGABIOS_REPO}" "${SRC_DIR}"
  else
    log "fetch updates in ${SRC_DIR}"
    git -C "${SRC_DIR}" fetch --tags --force origin
  fi

  log "checkout ${SEAVGABIOS_REF} (${SEAVGABIOS_COMMIT})"
  git -C "${SRC_DIR}" checkout --detach "${SEAVGABIOS_COMMIT}"

  local head
  head="$(git -C "${SRC_DIR}" rev-parse HEAD)"
  [[ "${head}" == "${SEAVGABIOS_COMMIT}" ]] || die "HEAD ${head} != pinned ${SEAVGABIOS_COMMIT}"
}

write_config() {
  log "write ${CONFIG_FILE}"
  mkdir -p "$(dirname "${CONFIG_FILE}")"
  cat >"${CONFIG_FILE}" <<'EOF'
# Generated by firmware/build-scripts/build-seavgabios.sh — do not edit.
# Remaining symbols are filled in by `make olddefconfig`.
CONFIG_QEMU=y
# CONFIG_NO_VGABIOS is not set
CONFIG_VGA_STANDARD_VGA=y
# CONFIG_VGA_VBE is not set
# CONFIG_VGA_PCI is not set
EOF
}

build_seavgabios() {
  mkdir -p "${BUILD_DIR}"
  log "make olddefconfig (KCONFIG_CONFIG=${CONFIG_FILE})"
  make -C "${SRC_DIR}" PYTHON="${PYTHON}" \
    KCONFIG_CONFIG="${CONFIG_FILE}" OUT="${BUILD_DIR}/" olddefconfig

  grep -q '^CONFIG_BUILD_VGABIOS=y$' "${CONFIG_FILE}" \
    || die "olddefconfig did not enable CONFIG_BUILD_VGABIOS in ${CONFIG_FILE}"
  grep -q '^CONFIG_VGA_STANDARD_VGA=y$' "${CONFIG_FILE}" \
    || die "olddefconfig dropped CONFIG_VGA_STANDARD_VGA in ${CONFIG_FILE}"

  log "make -j${JOBS} (OUT=${BUILD_DIR}/)"
  # `all` also builds bios.bin from the same tree; only vgabios.bin is installed.
  make -C "${SRC_DIR}" -j"${JOBS}" PYTHON="${PYTHON}" \
    KCONFIG_CONFIG="${CONFIG_FILE}" OUT="${BUILD_DIR}/" all
  [[ -f "${BUILD_DIR}/vgabios.bin" ]] || die "expected ${BUILD_DIR}/vgabios.bin after make"
}

# An option ROM starts with 55 AA, a 512-byte-block size at offset 2, and the
# declared extent must checksum to zero mod 256 (IBM PC option ROM convention).
# Fail loudly rather than install a ROM a firmware option-ROM scan would reject.
verify_option_rom() {
  "${PYTHON}" "${SCRIPT_DIR}/check-option-rom.py" "$1"
}

install_artifacts() {
  local rom_src="${BUILD_DIR}/vgabios.bin"
  local rom_dst="${OUT_DIR}/vgabios.bin"
  local size sha256 built_at

  log "verify ${rom_src}"
  verify_option_rom "${rom_src}"

  log "install ${rom_dst}"
  cp -f "${rom_src}" "${rom_dst}"

  if [[ -f "${SRC_DIR}/COPYING.LESSER" ]]; then
    cp -f "${SRC_DIR}/COPYING.LESSER" "${OUT_DIR}/COPYING.SeaVGABIOS"
  elif [[ -f "${SRC_DIR}/COPYING" ]]; then
    cp -f "${SRC_DIR}/COPYING" "${OUT_DIR}/COPYING.SeaVGABIOS"
  fi

  size="$(wc -c <"${rom_dst}" | tr -d ' ')"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256="$(sha256sum "${rom_dst}" | awk '{print $1}')"
  elif command -v shasum >/dev/null 2>&1; then
    sha256="$(shasum -a 256 "${rom_dst}" | awk '{print $1}')"
  else
    sha256="unavailable"
  fi
  built_at="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

  cat >"${OUT_DIR}/manifest.json" <<EOF
{
  "name": "seavgabios",
  "component": "vgabios.bin",
  "repo": "${SEAVGABIOS_REPO}",
  "ref": "${SEAVGABIOS_REF}",
  "commit": "${SEAVGABIOS_COMMIT}",
  "config": [
    "CONFIG_QEMU=y",
    "CONFIG_VGA_STANDARD_VGA=y",
    "CONFIG_VGA_VBE=n",
    "CONFIG_VGA_PCI=n"
  ],
  "license": "LGPL-3.0-or-later (see COPYING.SeaVGABIOS / upstream vgasrc headers)",
  "built_at_utc": "${built_at}",
  "size_bytes": ${size},
  "sha256": "${sha256}",
  "notes": "Build artifact only. Not vendored into MIT/Apache crates. No option-ROM scan in the emulator yet."
}
EOF

  # Shared pin record (no binary) for docs / CI.
  mkdir -p "${ROOT}/firmware/manifests"
  cat >"${ROOT}/firmware/manifests/seavgabios.json" <<EOF
{
  "name": "seavgabios",
  "component": "vgabios.bin",
  "repo": "${SEAVGABIOS_REPO}",
  "ref": "${SEAVGABIOS_REF}",
  "commit": "${SEAVGABIOS_COMMIT}",
  "config": [
    "CONFIG_QEMU=y",
    "CONFIG_VGA_STANDARD_VGA=y",
    "CONFIG_VGA_VBE=n",
    "CONFIG_VGA_PCI=n"
  ],
  "license": "LGPL-3.0-or-later",
  "output_path": "firmware/seavgabios/vgabios.bin",
  "build_script": "firmware/build-scripts/build-seavgabios.sh",
  "notes": "Pinned revision for reproducible builds. Binary is gitignored; rebuild locally or in Linux CI."
}
EOF

  log "wrote ${OUT_DIR}/manifest.json (${size} bytes, sha256=${sha256})"
  log "wrote ${ROOT}/firmware/manifests/seavgabios.json"
}

main() {
  check_host
  fetch_sources
  write_config
  build_seavgabios
  install_artifacts
  log "SeaVGABIOS build complete -> ${OUT_DIR}/vgabios.bin"
  log "Map with emulator-cli --option-rom (mapping only; no option-ROM scan yet)."
}

main "$@"
